### ISSUE TITLE
[SUGESTÃO] Adicionar detalhamento do Projeto no READ_ME.

### ISSUE THREAD

**Issue by gonzagadevs** [rluispdev/testGit#1]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
 Adicionar informações referentes ao Projeto.

**Descreva as alternativas que você considerou**
Criar uma descrição do motivo de ter-se criado o repositório testGit.

**Contexto adicional**
N/A

**Comment by rafaelluisgonzaga** [comment]
ok!
